package org.community.service.schemas.xml_error;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.6
 * Tue Feb 23 11:54:59 PST 2010
 * Generated source version: 2.2.6
 * 
 */

@WebFault(name = "faultdetails", targetNamespace = "http://service.community.org/schemas/xml_error/")
public class GrahakFaultDetails extends Exception {
    public static final long serialVersionUID = 20100223115459L;
    
    private org.community.service.schemas.xml_error.FaultdetailsT faultdetails;

    public GrahakFaultDetails() {
        super();
    }
    
    public GrahakFaultDetails(String message) {
        super(message);
    }
    
    public GrahakFaultDetails(String message, Throwable cause) {
        super(message, cause);
    }

    public GrahakFaultDetails(String message, org.community.service.schemas.xml_error.FaultdetailsT faultdetails) {
        super(message);
        this.faultdetails = faultdetails;
    }

    public GrahakFaultDetails(String message, org.community.service.schemas.xml_error.FaultdetailsT faultdetails, Throwable cause) {
        super(message, cause);
        this.faultdetails = faultdetails;
    }

    public org.community.service.schemas.xml_error.FaultdetailsT getFaultInfo() {
        return this.faultdetails;
    }
}
